"""add persona_scores table

Revision ID: 8a7355a4887c
Revises: ea7244c39792
Create Date: 2026-02-18 09:45:36.364071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7355a4887c'
down_revision: Union[str, None] = 'ea7244c39792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_scores',
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sycophancy', sa.Float(), nullable=False),
    sa.Column('hallucination', sa.Float(), nullable=False),
    sa.Column('over_confidence', sa.Float(), nullable=False),
    sa.Column('safety_bypass', sa.Float(), nullable=False),
    sa.Column('sales_pressure', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_scores')
    # ### end Alembic commands ###
